[WIP] update to he acknowledgments
astropy/astropy-v2.0-paper pull request #105
Opened 2017-12-14 16:42 UTC by crawfordsm

This is an update to the acknowledgments and will include several further updates.    This should be checked by those who included acknowledgements or any further that should be included.

2017-12-14 19:28 UTC, hamogu requested changes

2017-12-14 19:28 UTC, hamogu commented on main.tex
> +that have open issues and provided feedback, and have supported the
open -> opened

2017-12-14 19:28 UTC, hamogu commented on main.tex
> +We would like to thank the community that have contributed to \astropy,
have or has? Community would be singular, but do you want to say "those members of the community"? I'm a little confused and leave that up to a native speaker.

2018-01-04 11:57 UTC, bsipocz commented on main.tex
> +package.
subpackage

2018-01-04 19:28 UTC, merged