Refine modeling intro
astropy/astropy-v2.0-paper pull request #73
Opened 2017-12-07 15:41 UTC by pllim

Fix #43 

Please review -- @hugobuddel and @nden. I took the liberties to edit the text given in https://github.com/astropy/astropy-v2.0-paper/issues/43#issuecomment-349996742 a little, hope you don't mind.

2017-12-07 16:26 UTC, nden commented
@pllim Thanks for submitting a PR.

2017-12-08 09:28 UTC, hugobuddel commented
Thanks, @nden and @pllim, the section is nicer to read now IMHO.

Reading the source, I see that there already used to be a sentence that adding unit support makes the modeling packages especially useful for astronomy, which was commented out. (I just read the pdf earlier.) The new introduction has a similar sentence again.

2017-12-08 12:30 UTC, adrn requested changes

2017-12-08 12:30 UTC, adrn commented on main.tex
> +Tha \package{astropy.modeling} subpackage provides a framework for representing
"Tha" -> "The"

2017-12-08 12:30 UTC, adrn commented on main.tex
> +The main motivation for it was creating a framework
A few grammar things: "The main motivation for this functionality was to create a framework that allows arbitrary combination of models to..."

2017-12-08 12:30 UTC, adrn commented on main.tex
> +The current FITS WCS model lacks the flexibility to represent
The use of "model" here is different than in above (one of the reasons I dislike the word - it is too overloaded in english!). Maybe change to "The current FITS WCS specification lacks the..."

2017-12-08 12:30 UTC, adrn commented on main.tex
> +The addition of units to modeling made it attractive for representing
I don't like the passive voice here. Maybe: "The fact that the \astropypkg modeling framework now supports propagating units also makes it a useful tool for representing and fitting astrophysical models within data analysis tools."

2017-12-08 19:46 UTC, pllim commented
Thank you for the reviews. I think I have addressed all the comments.

2017-12-09 02:30 UTC, adrn approved these changes

2017-12-09 02:30 UTC, merged